/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class FireBulletReq : TBase
{
  private ProtocolBase _header;
  private Vector3 _dir;

  public ProtocolBase Header
  {
    get
    {
      return _header;
    }
    set
    {
      __isset.header = true;
      this._header = value;
    }
  }

  public Vector3 Dir
  {
    get
    {
      return _dir;
    }
    set
    {
      __isset.dir = true;
      this._dir = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool header;
    public bool dir;
  }

  public FireBulletReq() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.Struct) {
            Header = new ProtocolBase();
            Header.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.Struct) {
            Dir = new Vector3();
            Dir.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("FireBulletReq");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (Header != null && __isset.header) {
      field.Name = "header";
      field.Type = TType.Struct;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      Header.Write(oprot);
      oprot.WriteFieldEnd();
    }
    if (Dir != null && __isset.dir) {
      field.Name = "dir";
      field.Type = TType.Struct;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      Dir.Write(oprot);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("FireBulletReq(");
    bool __first = true;
    if (Header != null && __isset.header) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Header: ");
      __sb.Append(Header== null ? "<null>" : Header.ToString());
    }
    if (Dir != null && __isset.dir) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Dir: ");
      __sb.Append(Dir== null ? "<null>" : Dir.ToString());
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

