/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class MoveReq : TBase
{
  private ProtocolBase _header;
  private Vector3 _goal;

  public ProtocolBase Header
  {
    get
    {
      return _header;
    }
    set
    {
      __isset.header = true;
      this._header = value;
    }
  }

  public Vector3 Goal
  {
    get
    {
      return _goal;
    }
    set
    {
      __isset.goal = true;
      this._goal = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool header;
    public bool goal;
  }

  public MoveReq() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.Struct) {
            Header = new ProtocolBase();
            Header.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.Struct) {
            Goal = new Vector3();
            Goal.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("MoveReq");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (Header != null && __isset.header) {
      field.Name = "header";
      field.Type = TType.Struct;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      Header.Write(oprot);
      oprot.WriteFieldEnd();
    }
    if (Goal != null && __isset.goal) {
      field.Name = "goal";
      field.Type = TType.Struct;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      Goal.Write(oprot);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("MoveReq(");
    bool __first = true;
    if (Header != null && __isset.header) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Header: ");
      __sb.Append(Header== null ? "<null>" : Header.ToString());
    }
    if (Goal != null && __isset.goal) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Goal: ");
      __sb.Append(Goal== null ? "<null>" : Goal.ToString());
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

