/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum Protocol
{
  LOGIN = 1,
  MOVE = 2,
  SOMEONE_JOIN = 3,
  CREATURE_STATE = 4,
  FIRE_BULLET = 5,
  LOGOUT = 6,
}
