/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class ProtocolReqBase : TBase
{
  private Protocol _pid;

  /// <summary>
  /// 
  /// <seealso cref="Protocol"/>
  /// </summary>
  public Protocol Pid
  {
    get
    {
      return _pid;
    }
    set
    {
      __isset.pid = true;
      this._pid = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool pid;
  }

  public ProtocolReqBase() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.I32) {
            Pid = (Protocol)iprot.ReadI32();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("ProtocolReqBase");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (__isset.pid) {
      field.Name = "pid";
      field.Type = TType.I32;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32((int)Pid);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("ProtocolReqBase(");
    bool __first = true;
    if (__isset.pid) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Pid: ");
      __sb.Append(Pid);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

