/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sample.idl.shared;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-4-27")
public class SharedStructV4 implements org.apache.thrift.TBase<SharedStructV4, SharedStructV4._Fields>, java.io.Serializable, Cloneable, Comparable<SharedStructV4> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SharedStructV4");

  private static final org.apache.thrift.protocol.TField KEY1_FIELD_DESC = new org.apache.thrift.protocol.TField("key1", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField NAME1_FIELD_DESC = new org.apache.thrift.protocol.TField("name1", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SharedStructV4StandardSchemeFactory());
    schemes.put(TupleScheme.class, new SharedStructV4TupleSchemeFactory());
  }

  public int key1; // required
  public String name1; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    KEY1((short)1, "key1"),
    NAME1((short)2, "name1");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // KEY1
          return KEY1;
        case 2: // NAME1
          return NAME1;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __KEY1_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.KEY1, new org.apache.thrift.meta_data.FieldMetaData("key1", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NAME1, new org.apache.thrift.meta_data.FieldMetaData("name1", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SharedStructV4.class, metaDataMap);
  }

  public SharedStructV4() {
  }

  public SharedStructV4(
    int key1,
    String name1)
  {
    this();
    this.key1 = key1;
    setKey1IsSet(true);
    this.name1 = name1;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SharedStructV4(SharedStructV4 other) {
    __isset_bitfield = other.__isset_bitfield;
    this.key1 = other.key1;
    if (other.isSetName1()) {
      this.name1 = other.name1;
    }
  }

  public SharedStructV4 deepCopy() {
    return new SharedStructV4(this);
  }

  @Override
  public void clear() {
    setKey1IsSet(false);
    this.key1 = 0;
    this.name1 = null;
  }

  public int getKey1() {
    return this.key1;
  }

  public SharedStructV4 setKey1(int key1) {
    this.key1 = key1;
    setKey1IsSet(true);
    return this;
  }

  public void unsetKey1() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __KEY1_ISSET_ID);
  }

  /** Returns true if field key1 is set (has been assigned a value) and false otherwise */
  public boolean isSetKey1() {
    return EncodingUtils.testBit(__isset_bitfield, __KEY1_ISSET_ID);
  }

  public void setKey1IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __KEY1_ISSET_ID, value);
  }

  public String getName1() {
    return this.name1;
  }

  public SharedStructV4 setName1(String name1) {
    this.name1 = name1;
    return this;
  }

  public void unsetName1() {
    this.name1 = null;
  }

  /** Returns true if field name1 is set (has been assigned a value) and false otherwise */
  public boolean isSetName1() {
    return this.name1 != null;
  }

  public void setName1IsSet(boolean value) {
    if (!value) {
      this.name1 = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case KEY1:
      if (value == null) {
        unsetKey1();
      } else {
        setKey1((Integer)value);
      }
      break;

    case NAME1:
      if (value == null) {
        unsetName1();
      } else {
        setName1((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case KEY1:
      return Integer.valueOf(getKey1());

    case NAME1:
      return getName1();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case KEY1:
      return isSetKey1();
    case NAME1:
      return isSetName1();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SharedStructV4)
      return this.equals((SharedStructV4)that);
    return false;
  }

  public boolean equals(SharedStructV4 that) {
    if (that == null)
      return false;

    boolean this_present_key1 = true;
    boolean that_present_key1 = true;
    if (this_present_key1 || that_present_key1) {
      if (!(this_present_key1 && that_present_key1))
        return false;
      if (this.key1 != that.key1)
        return false;
    }

    boolean this_present_name1 = true && this.isSetName1();
    boolean that_present_name1 = true && that.isSetName1();
    if (this_present_name1 || that_present_name1) {
      if (!(this_present_name1 && that_present_name1))
        return false;
      if (!this.name1.equals(that.name1))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_key1 = true;
    list.add(present_key1);
    if (present_key1)
      list.add(key1);

    boolean present_name1 = true && (isSetName1());
    list.add(present_name1);
    if (present_name1)
      list.add(name1);

    return list.hashCode();
  }

  @Override
  public int compareTo(SharedStructV4 other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetKey1()).compareTo(other.isSetKey1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKey1()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.key1, other.key1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetName1()).compareTo(other.isSetName1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName1()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name1, other.name1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SharedStructV4(");
    boolean first = true;

    sb.append("key1:");
    sb.append(this.key1);
    first = false;
    if (!first) sb.append(", ");
    sb.append("name1:");
    if (this.name1 == null) {
      sb.append("null");
    } else {
      sb.append(this.name1);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SharedStructV4StandardSchemeFactory implements SchemeFactory {
    public SharedStructV4StandardScheme getScheme() {
      return new SharedStructV4StandardScheme();
    }
  }

  private static class SharedStructV4StandardScheme extends StandardScheme<SharedStructV4> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SharedStructV4 struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // KEY1
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.key1 = iprot.readI32();
              struct.setKey1IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NAME1
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name1 = iprot.readString();
              struct.setName1IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SharedStructV4 struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(KEY1_FIELD_DESC);
      oprot.writeI32(struct.key1);
      oprot.writeFieldEnd();
      if (struct.name1 != null) {
        oprot.writeFieldBegin(NAME1_FIELD_DESC);
        oprot.writeString(struct.name1);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SharedStructV4TupleSchemeFactory implements SchemeFactory {
    public SharedStructV4TupleScheme getScheme() {
      return new SharedStructV4TupleScheme();
    }
  }

  private static class SharedStructV4TupleScheme extends TupleScheme<SharedStructV4> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SharedStructV4 struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetKey1()) {
        optionals.set(0);
      }
      if (struct.isSetName1()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetKey1()) {
        oprot.writeI32(struct.key1);
      }
      if (struct.isSetName1()) {
        oprot.writeString(struct.name1);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SharedStructV4 struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.key1 = iprot.readI32();
        struct.setKey1IsSet(true);
      }
      if (incoming.get(1)) {
        struct.name1 = iprot.readString();
        struct.setName1IsSet(true);
      }
    }
  }

}

