/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sample.HelloGame.idl;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Protocol implements org.apache.thrift.TEnum {
  LOGIN(1),
  MOVE(2),
  SOMEONE_JOIN(3),
  CREATURE_STATE(4),
  FIRE_BULLET(5),
  LOGOUT(6);

  private final int value;

  private Protocol(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Protocol findByValue(int value) { 
    switch (value) {
      case 1:
        return LOGIN;
      case 2:
        return MOVE;
      case 3:
        return SOMEONE_JOIN;
      case 4:
        return CREATURE_STATE;
      case 5:
        return FIRE_BULLET;
      case 6:
        return LOGOUT;
      default:
        return null;
    }
  }
}
